### ISSUE TITLE
bootstrap.py failing to complete

### ISSUE THREAD

**Issue by archerrbgh** [chrismattmann/etllib#37]
@chrismattmann 

When running on OS X 10.10.2, bootstrap.py fails when called during installation, giving the following error: "[Errno 54] Connection reset by peer". It seems as if the error is occurring at line 159 in bootstrap.py: "if subprocess.call(cmd, env=dict(os.environ, PYTHONPATH=setuptools_path)) != 0:".

**Comment by archerrbgh** [comment]
I started over, and tried to install setuptools using the following command: "../altpython/bin/easy_install-2.7  -U setuptools"

However, I got the following error message:
"Searching for setuptools
Reading http://oodt.jpl.nasa.gov/dist
error: [Errno 54] Connection reset by peer"

I also tried to run bootstrap.py by doing the following: "~/Downloads/altpython/bin/python2.7 bootstrap.py -d".

However, I got the following error: "bootstrap.py: error: no such option: -d". Is this because the setuptools installation was not properly run?

**Comment by dongnizh** [comment]
@archerrbgh please see #36 for solution.

**Comment by archerrbgh** [comment]
@dongnizh Thank you very much for showing me how to fix it! I was able to run bootstrap.py, but I am now having issues running bin/buildout install with-tika. The error message given was:

"No eggs found in /var/folders/1g/8ls00_s17130fh74x7t8f18c0000gn/T/tmp8tBi83get_dist/tika-python.git/egg-dist-tmp-vmgnMo (setup script problem?)
While:
  Installing with-tika.
  Getting distribution for 'tika>=1.6'.
Error: Couldn't install: tika 1.6"

Would you happen to know how to fix this? Thanks.

**Comment by dongnizh** [comment]
I have not faced that problem. However, you need to make sure you are using the new buildout python to run with-tike installation. Otherwise, the default python can not find tike1.6. You can test whether you are using the correct python version by typing 

```

Last login: Mon Feb  2 21:04:53 on ttys001
zhaodongnis-MacBook-Pro:~ zhaodongni$ cd ~/Documents/etllib/
zhaodongnis-MacBook-Pro:etllib zhaodongni$ ./buildout.python/python-2.7/bin/python2.7 
Python 2.7.9 (default, Feb  2 2015, 19:08:02) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tika
>>> 

```
This is used to make sure you have "tika module" inside your python.

**Comment by archerrbgh** [comment]
Hi @dongnizh 

I ended starting over because I had messed up somewhere in the middle, and got import tika to work on my original Python instead of the newly installed one. I have finally gotten everything to work now! Thanks a lot for the help!
