### ISSUE TITLE
merge tika-image-similarity into ETLlib

### ISSUE THREAD

**Issue by dongnizh** [chrismattmann/etllib#48]

**Comment by chrismattmann** [comment]
Yep we need to bring the portions of http://github.com/chrismattmann/tika-img-similarity functionality into etl/etllib.py and then expose that functionality in tika-img-similarity

**Comment by dongnizh** [comment]
Hi @chrismattmann  GOOD NEWS!!! I tried to run image similarity and works fine with different formats of images. Will upgrade this image similarity tool to be applicable for all.

**Comment by chrismattmann** [comment]
That is awesome Dongni! Woot @dongnizh
